### ISSUE TITLE
doesn't work with gradle 2.11

### ISSUE THREAD

**Issue by zfy0701** [johnrengelman/gradle-processes#8]
begin from gradle 2.11, it seems there is api change that breaks the plugin

```
Caused by: java.lang.NoSuchMethodError: org.gradle.process.internal.ExecHandleBuilder.<init>(Lorg/gradle/api/internal/file/FileResolver;)V
    at com.github.jengelman.gradle.plugins.processes.internal.DefaultForkAction.<init>(DefaultForkAction.java:15)
    at com.github.jengelman.gradle.plugins.processes.internal.DefaultProcessOperations.newForkAction(DefaultProcessOperations.groovy:85)
    at com.github.jengelman.gradle.plugins.processes.internal.ForkActionFactory$newForkAction.call(Unknown Source)
    at com.github.jengelman.gradle.plugins.processes.ProcessesExtension.newForkAction(ProcessesExtension.groovy)
    at com.github.jengelman.gradle.plugins.processes.internal.ForkActionFactory$newForkAction.call(Unknown Source)
    at com.github.jengelman.gradle.plugins.processes.tasks.Fork.<init>(Fork.groovy:23)
    at com.github.jengelman.gradle.plugins.processes.tasks.Fork_Decorated.<init>(Unknown Source)
    at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:48)
    at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
    at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:121)
```

**Comment by dpr-rec** [comment]
Is this plugin still maintained? I'm depending on it, as it is a transitive dependency of https://github.com/robfletcher/gradle-compass.

**Comment by guspower** [comment]
I took [a quick pass](https://github.com/guspower/gradle-processes) at getting the plugin to work against gradle 4.5. There have unsurprisingly been a few changes since pre-2.11 but I've tried to keep the plugin changes to a minimum. 

@johnrengelman is this something you'd be willing to consider a pull request for?

**Comment by kungfoo** [comment]
This should be fixed with the new relese `0.4.x` of the plugin.
